development:
  adapter: sqlite3
  database: db/development.sqlite
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: production
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost